import axios from 'axios';

interface WhatsAppMessage {
  messaging_product: string;
  to: string;
  type: string;
  text: {
    body: string;
  };
}

export async function sendWhatsAppMessage(phoneNumber: string, message: string): Promise<boolean> {
  try {
    const accessToken = import.meta.env.VITE_WHATSAPP_ACCESS_TOKEN;
    const phoneNumberId = import.meta.env.VITE_WHATSAPP_PHONE_NUMBER_ID;
    
    if (!accessToken || !phoneNumberId) {
      console.error('WhatsApp credentials not configured');
      return false;
    }
    
    // Format phone number (remove any non-numeric characters)
    const formattedPhone = phoneNumber.replace(/\D/g, '');
    
    // Add country code if not present
    const fullPhoneNumber = formattedPhone.startsWith('1') ? formattedPhone : `1${formattedPhone}`;
    
    const payload: WhatsAppMessage = {
      messaging_product: "whatsapp",
      to: fullPhoneNumber,
      type: "text",
      text: {
        body: message
      }
    };
    
    console.log('Sending WhatsApp message to:', fullPhoneNumber);
    
    const response = await axios.post(
      `https://graph.facebook.com/v17.0/${phoneNumberId}/messages`,
      payload,
      {
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json'
        }
      }
    );
    
    console.log('WhatsApp API response:', response.data);
    return true;
  } catch (error) {
    console.error('Error sending WhatsApp message:', error);
    return false;
  }
}

export async function sendSEOContentViaWhatsApp(phoneNumber: string, seoContent: any): Promise<boolean> {
  try {
    // Format the SEO content into a readable message
    const message = `
*SEO Content Generated*

*Title:* ${seoContent.seoTitle}

*Meta Description:* ${seoContent.metaDescription}

*Keywords:* ${seoContent.keywords.join(', ')}

*Product Description:* ${seoContent.productDescription}

*Long-tail Keywords:* ${seoContent.longTailKeywords.join(', ')}

*Product Features:*
${seoContent.productFeatures.map((feature: string) => `• ${feature}`).join('\n')}

*Target Audience:*
${seoContent.targetAudience.map((audience: string) => `• ${audience}`).join('\n')}

*SEO Recommendations:*
${seoContent.seoRecommendations.map((rec: string) => `• ${rec}`).join('\n')}

*Competitor Analysis:*
${seoContent.competitorAnalysis}

*Content Ideas:*
${seoContent.contentIdeas.map((idea: string) => `• ${idea}`).join('\n')}

Generated by Trend Whisper SEO Generator
    `.trim();
    
    return await sendWhatsAppMessage(phoneNumber, message);
  } catch (error) {
    console.error('Error formatting and sending SEO content via WhatsApp:', error);
    return false;
  }
} 